run_command:
  mpc_server: "python $CAR_WS_PATH/src/ackerman_ros_robot_gazebo_simulation/custom_controllers/ackermann-drive-teleop/script_for_mpc_prod/mpc_server_simplified_rl.py"
  unpause_physics: "rosservice call /gazebo/unpause_physics"
  mpc_node: "rosrun ackermann_drive_teleop mpc_node_simplified_rl.py"
  motion_planner: "roslaunch $CAR_WS_PATH/src/motion_planner/launch/motion_planner.launch"
timeout: 200
path_files: "test"
user_prefix_path: "/home/vialab"
eval_results_path: "/src/MPCSimulationRunner/data/eval_test/"
workspace_list: ["car_ws"] 
sleep_list: [1, 3, 2, 1]