# Path generation configuration
# Map selection: 1 = physics_building, 2 = ee_building
map_choice: 1
# Path difficulty: options are 'easy', 'hard', 'moderate'
path_difficulty: easy
# Number of paths to generate
total_paths_to_generate: 400
# Toggles
manual_path_generation: false
testing: false
use_pre_load_map: true
# Inflation radius for collision checking [m]
inflation_radius: 1.25