# Workflow for checking the integrity of datasets to ensure that they have not been tampered with or corrupted.
name: Dataset Integrity Check

on:
  push:
    branches:
      - main 
      - dev

jobs:
  check_integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch complete repository history

      - name: Print working directory before cd
        run: pwd

      - name: Change directory to data
        run: cd path_datasets

      - name: Print working directory after cd
        run: pwd

      - name: List directory contents
        run: ls -l path_datasets 

      - name: Calculate checksums for train data
        run: |
          find train -name "*.csv" -type f -exec sha256sum {} \; > new_checksums_train.txt

      - name: Calculate checksums for test data
        run: |
          find test -name "*.csv" -type f -exec sha256sum {} \; > new_checksums_test.txt

      - name: Compare train checksums
        run: diff checksums_train.txt new_checksums_train.txt

      - name: Compare test checksums
        run: diff checksums_test.txt new_checksums_test.txt

      - name: Fail if differences found
        if: failure()
        run: echo "Data integrity check failed, please check the differences above" && exit 1
