name: Docker Build and Test

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
      - dev
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests against the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true # 'load: true' makes the image available to the next step
          tags: path-following-env:latest

      - name: Smoke test the container
        run: |
          echo "Starting container for a 30-seconds smoke test..."
          
          # Run the container with a 30-seconds timeout.
          timeout 30s docker run --rm --workdir /home/ubuntu/path-following-datasets/examples/ \
            path-following-env:latest \
            bash runSimulator.sh
          
          # Check the exit code of the 'timeout' command.
          status=$?
          
          # Exit code 124 means it timed out. Exit code 0 means it finished before 5s.
          # We consider both of these a success for a smoke test.
          if [ $status -eq 124 ] || [ $status -eq 0 ]; then
            echo "✅ Docker working normally. Smoke test passed."
            exit 0 # Explicitly exit with success code.
          else
            echo "❌ Error: Container exited with an unexpected status code: $status"
            exit $status # Exit with the original error code to fail the job.
          fi

      - name: Verify Conda environment
        run: |
          docker run -it path-following-env:latest /bin/bash -c "conda info && conda env list"

      - name: Verify ROS installation
        run: |
          docker run -it path-following-env:latest /bin/bash -c "source /opt/ros/melodic/setup.bash && rospack list"
