name: Docker Build and Test

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
      - dev
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests against the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true # 'load: true' makes the image available to the next step
          no-cache: true
          tags: path-following-env:latest

      - name: Verify Conda environment
        run: |
          docker run --rm path-following-env:latest bash -c "conda info && conda env list"

      - name: Verify ROS installation
        run: |
          docker run --rm path-following-env:latest rospack list

      - name: Smoke test the container with supervisord
        run: |
          echo "Starting container for a 30-second smoke test..."

          # We wrap the command in an if/else structure to control the flow.
          # This works correctly with GitHub's "fail-fast" mode.
          if timeout 30s docker run --rm --user root path-following-env:latest \
            /usr/bin/supervisord -c /etc/supervisor/supervisord.conf; then
            
            # This block only runs if the exit code was 0 (the container finished early)
            echo "✅ Docker working normally. Smoke test passed."
            exit 0
          else
            # This block runs for ANY non-zero exit code
            status=$?
            if [ $status -eq 124 ]; then
              # The command timed out, which we consider a success for this test
              echo "✅ Docker working normally. Smoke test passed."
              exit 0
            else
              # The command failed with a different error code
              echo "❌ Error: Container exited with an unexpected status code: $status"
              exit $status
            fi
          fi